# Generated by Django 2.2.2 on 2020-02-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestform',
            name='secret_key',
            field=models.CharField(default='###############', max_length=50),
        ),
    ]
