# Generated by Django 2.2.2 on 2020-02-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_interestform_secret_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=2)),
                ('shortlisted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='interestform',
            name='interest',
        ),
        migrations.AddField(
            model_name='interestform',
            name='pincode',
            field=models.CharField(default='######', max_length=10),
        ),
    ]
