# Generated by Django 2.2.2 on 2020-02-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200205_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceform',
            name='grade',
            field=models.CharField(default='#', max_length=2),
        ),
    ]
