# Generated by Django 2.2.2 on 2020-02-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200205_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceform',
            name='email',
            field=models.CharField(default='example@example.com', max_length=100),
        ),
    ]
