# Generated by Django 2.2.2 on 2020-02-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_experienceform_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceform',
            name='description',
            field=models.TextField(default='No Description'),
        ),
    ]
