# Generated by Django 2.2.2 on 2020-02-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_experienceform_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceform',
            name='grade',
            field=models.CharField(default='N/A', max_length=2),
        ),
    ]
