# Generated by Django 2.2.2 on 2020-02-06 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200206_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneInterview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('timing', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade', models.CharField(default='N/A', max_length=2)),
            ],
        ),
    ]
