# Generated by Django 2.2.2 on 2020-02-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_phoneinterview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneinterview',
            name='timing',
            field=models.CharField(max_length=100),
        ),
    ]
