# Generated by Django 2.2.2 on 2020-02-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200206_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneinterview',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
