# Generated by Django 2.2.2 on 2020-02-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_phoneinterview_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneinterview',
            name='timing',
            field=models.CharField(default='Not Confirmed', max_length=100),
        ),
    ]
